<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_flexible-ui',
		'title' => 'Flexible UI',
		'fields' => array (
			array (
				'key' => 'field_55115f8db4c12',
				'label' => 'Flexible Content',
				'name' => 'flex_ui',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Slide Show',
						'name' => 'slide_show',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_551184f125c44',
								'label' => 'Slide Images',
								'name' => 'slide_imgs',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_5511850d25c45',
										'label' => 'Image',
										'name' => 'slide_img',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_55217bbce5e72',
										'label' => 'Caption Text',
										'name' => 'slide_caption',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_552180b98fc48',
										'label' => 'Caption Title',
										'name' => 'slide_caption_title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add an image',
							),
							array (
								'key' => 'field_5511853725c47',
								'label' => 'Title',
								'name' => 'slide_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5511854d25c49',
								'label' => 'Text',
								'name' => 'slide_text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_551b5eb158c5b',
								'label' => 'Full width mobile slide?',
								'name' => 'slide_img_full',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_551dd2fc7ec3c',
								'label' => 'Image alignment',
								'name' => 'slide_align',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'Middle' => 'Middle',
									'Top' => 'Top',
									'Bottom' => 'Bottom',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'Middle',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_55218635d52a7',
								'label' => 'Text alignment',
								'name' => 'slide_align_text',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'Top' => 'Top',
									'Middle' => 'Middle',
									'Bottom' => 'Bottom',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'Middle',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_551dce822aa1a',
								'label' => 'Remove padding from wrapper?',
								'name' => 'slide_nopadding',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_552192490b3ac',
								'label' => 'No border bottom?',
								'name' => 'no_border_bottom',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
						),
					),
					array (
						'label' => 'Swiper',
						'name' => 'swiper',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_551c634a7cd06',
								'label' => 'Slide Images',
								'name' => 'slide_imgs',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_551c634a7cd07',
										'label' => 'Image',
										'name' => 'slide_img',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add an image',
							),
							array (
								'key' => 'field_551c634a7cd08',
								'label' => 'Section title',
								'name' => 'section_intro_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551c634a7cd09',
								'label' => 'Section text',
								'name' => 'section_intro_text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_551d551d4614b',
								'label' => 'Section CTA',
								'name' => 'section_cta',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551d55254614c',
								'label' => 'Section CTA link',
								'name' => 'section_cta_link',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551eb6fe34f85',
								'label' => 'Full width CTA button?',
								'name' => 'section_cta_full',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_551eb90b1e465',
								'label' => 'CTA icon class',
								'name' => 'section_cta_icon',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
					),
					array (
						'label' => 'Image & Text Column',
						'name' => 'column_switch',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5522ef4100d27',
								'label' => 'Section title',
								'name' => 'section_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_55231a8200b5b',
								'label' => 'Twitter handle',
								'name' => 'twitter_handle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551185a0a8e56',
								'label' => 'Image',
								'name' => 'col_sw_img',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_551185a0a8e58',
								'label' => 'Title',
								'name' => 'col_sw_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551185a0a8e59',
								'label' => 'Text',
								'name' => 'col_sw_text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_551185a0a8e55',
								'label' => 'Image on which side?',
								'name' => 'col_sw_start',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'Left' => 'Left',
									'Right' => 'Right',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_551186b6e304f',
								'label' => 'Image vertical alignment',
								'name' => 'slide_align',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'Top' => 'Top',
									'Middle' => 'Middle',
									'Bottom' => 'Bottom',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
							),
							array (
								'key' => 'field_551ad86242faf',
								'label' => 'Top align text?',
								'name' => 'col_sw_text_top',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_551ad6d512840',
								'label' => 'Title goes above columns?',
								'name' => 'col_sw_title_top',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_551b49f5b681f',
								'label' => '70/30 Layout?',
								'name' => 'col_sw_7030',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_552190f5305d1',
								'label' => 'Border?',
								'name' => 'section_border',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'' => '',
									'top' => 'Top',
									'bottom' => 'Bottom',
									'both' => 'Both',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_553030205dc27',
								'label' => 'Image Link',
								'name' => 'image_link',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_55c7ac6ff2848',
								'label' => 'Background color',
								'name' => 'col_bg_color',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'' => '',
									'bluelite' => 'Light Blue',
									'graylite3' => 'Light Gray',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_56a6433729fb6',
								'label' => 'Button link',
								'name' => 'btn_link',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_56a6435d29fb7',
								'label' => 'Button text',
								'name' => 'btn_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_56a6436d29fb8',
								'label' => 'Button goes with...',
								'name' => 'btn_with',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'text' => 'text',
									'image' => 'image',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'horizontal',
							),
						),
					),
					array (
						'label' => 'Floated Image & Caption',
						'name' => 'float_caption',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_55117e45adcad',
								'label' => 'Image',
								'name' => 'float_img_cap_img',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_55117e61adcae',
								'label' => 'Mobile Image',
								'name' => 'float_img_cap_img_mob',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_55117eb5adcaf',
								'label' => 'Text',
								'name' => 'float_img_cap_text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Header Block - Full Width',
						'name' => 'header_block_full',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_55c78d5d1f491',
								'label' => 'Title',
								'name' => 'header_block_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_55c78d5d1f492',
								'label' => 'Text',
								'name' => 'header_block_text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_55c78dd51f499',
								'label' => 'Scale text down to sub-header sizes?',
								'name' => 'is_sub_header',
								'type' => 'true_false',
								'instructions' => 'Should the font size of the text be reduced to sub-header sizes?',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_55c78d5d1f493',
								'label' => 'Button link',
								'name' => 'header_block_link',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_55c78d5d1f494',
								'label' => 'Button text',
								'name' => 'header_block_btn_txt',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_55c78d991f498',
								'label' => 'Button type',
								'name' => 'header_block_btn_type',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'primary' => 'Primary',
									'secondary' => 'Secondary',
								),
								'default_value' => 'primary',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_55c78d5d1f495',
								'label' => 'Open link in new window?',
								'name' => 'new_window',
								'type' => 'true_false',
								'instructions' => 'Should this link open in a new window?',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_55c78d5d1f497',
								'label' => 'Background overlay image',
								'name' => 'header_block_bg_img',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_55dca4b232af9',
								'label' => 'No padding bottom',
								'name' => 'no_padding_bottom',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
						),
					),
					array (
						'label' => 'Color Block - Full Width',
						'name' => 'color_block_full',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_551ebe41a706a',
								'label' => 'Title',
								'name' => 'color_block_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551180f837d9f',
								'label' => 'Text',
								'name' => 'color_block_text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_5511810e37da0',
								'label' => 'Button link',
								'name' => 'color_block_link',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5511812137da1',
								'label' => 'Button text',
								'name' => 'color_block_btn',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5522dcba21c0c',
								'label' => 'Open link in new window?',
								'name' => 'new_window',
								'type' => 'true_false',
								'instructions' => 'Should this link open in a new window?',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_5511813637da2',
								'label' => 'Background color',
								'name' => 'color_block_bg',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'' => '',
									'Turquoise' => 'Turquoise',
									'Leaf' => 'Leaf',
									'Orange' => 'Orange',
									'Cranberry' => 'Cranberry',
									'Orange-red' => 'Orange-red',
									'Yellow' => 'Yellow',
									'Green' => 'Green',
									'Blue' => 'Blue',
									'Red' => 'Red',
									'Purple' => 'Purple',
								),
								'default_value' => '',
								'allow_null' => 1,
								'multiple' => 0,
							),
							array (
								'key' => 'field_551ac3c2fac8f',
								'label' => 'Background overlay image',
								'name' => 'color_block_bg_img',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
						),
					),
					array (
						'label' => 'Color Block - Blockquote',
						'name' => 'color_block_quote',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_551abe2ea97e4',
								'label' => 'Text',
								'name' => 'color_block_text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_551abe42a97e8',
								'label' => 'Author',
								'name' => 'color_block_author',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551abe2ea97e5',
								'label' => 'Button link',
								'name' => 'color_block_link',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551abe2ea97e6',
								'label' => 'Button text',
								'name' => 'color_block_btn',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551abe2ea97e7',
								'label' => 'Background color',
								'name' => 'color_block_bg',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'Turquoise' => 'Turquoise',
									'Leaf' => 'Leaf',
									'Orange' => 'Orange',
									'Cranberry' => 'Cranberry',
									'Orange-red' => 'Orange-red',
									'Yellow' => 'Yellow',
									'Green' => 'Green',
									'Blue' => 'Blue',
									'Red' => 'Red',
									'Purple' => 'Purple',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_551ac3f5fac90',
								'label' => 'Background overlay image',
								'name' => 'color_block_bg_img',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_551dbd1abe4e2',
								'label' => 'Align right?',
								'name' => 'color_block_right',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
						),
					),
					array (
						'label' => 'Color Block - Half',
						'name' => 'color_block_half',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_551ac07a118f0',
								'label' => 'Block',
								'name' => 'color_block_halves',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_551ac0c5118f1',
										'label' => 'Text',
										'name' => 'color_block_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551ac1a8513e0',
										'label' => 'Block link',
										'name' => 'color_block_link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551ac11f118f5',
										'label' => 'Image',
										'name' => 'color_block_img',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_551ac0d2118f2',
										'label' => 'Button link',
										'name' => 'color_block_btn_link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551ac0e4118f3',
										'label' => 'Button text',
										'name' => 'color_block_btn',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551ac0fd118f4',
										'label' => 'Background color',
										'name' => 'color_block_bg',
										'type' => 'select',
										'column_width' => '',
										'choices' => array (
											'Turquoise' => 'Turquoise',
											'Leaf' => 'Leaf',
											'Orange' => 'Orange',
											'Cranberry' => 'Cranberry',
											'Orange-red' => 'Orange-red',
											'Yellow' => 'Yellow',
											'Green' => 'Green',
											'Blue' => 'Blue',
											'Red' => 'Red',
										),
										'default_value' => '',
										'allow_null' => 0,
										'multiple' => 0,
									),
								),
								'row_min' => 2,
								'row_limit' => 2,
								'layout' => 'row',
								'button_label' => 'Add a color block',
							),
							array (
								'key' => 'field_5522ebf77596e',
								'label' => 'Hide',
								'name' => 'hide',
								'type' => 'true_false',
								'instructions' => 'Hide this block on the page (temporarily disable)',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
						),
					),
					array (
						'label' => 'Color Block - Third',
						'name' => 'color_block_third',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_551ac172513d9',
								'label' => 'Block',
								'name' => 'color_block_thirds',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_55ca47ee9f660',
										'label' => 'Title',
										'name' => 'color_block_title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551ac172513da',
										'label' => 'Text',
										'name' => 'color_block_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551ac187513df',
										'label' => 'Block link',
										'name' => 'color_block_link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551ac172513de',
										'label' => 'Image',
										'name' => 'color_block_img',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_551ac172513db',
										'label' => 'Button link',
										'name' => 'color_block_btn_link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551ac172513dc',
										'label' => 'Button text',
										'name' => 'color_block_btn',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551ac172513dd',
										'label' => 'Background color',
										'name' => 'color_block_bg',
										'type' => 'select',
										'column_width' => '',
										'choices' => array (
											'Turquoise' => 'Turquoise',
											'Leaf' => 'Leaf',
											'Orange' => 'Orange',
											'Cranberry' => 'Cranberry',
											'Orange-red' => 'Orange-red',
											'Yellow' => 'Yellow',
											'Green' => 'Green',
											'Blue' => 'Blue',
											'Red' => 'Red',
										),
										'default_value' => '',
										'allow_null' => 0,
										'multiple' => 0,
									),
								),
								'row_min' => 3,
								'row_limit' => 3,
								'layout' => 'row',
								'button_label' => 'Add a color block',
							),
							array (
								'key' => 'field_552155c434c90',
								'label' => 'No padding bottom',
								'name' => 'no_padding_bottom',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_552155dc34c91',
								'label' => 'No padding top',
								'name' => 'no_padding_top',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
						),
					),
					array (
						'label' => 'Third Columns',
						'name' => 'icon_thirds',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_551c4f1b4e908',
								'label' => 'Section title',
								'name' => 'section_intro_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551acd153c966',
								'label' => 'Section text',
								'name' => 'section_intro_text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_55cbd54558e38',
								'label' => 'Section border',
								'name' => 'section_border',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'' => '',
									'top' => 'Top',
									'bottom' => 'Bottom',
									'both' => 'Both',
								),
								'default_value' => 'both',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_551c56de2b099',
								'label' => 'CTA button text',
								'name' => 'section_cta',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551c56f42b09a',
								'label' => 'CTA Link',
								'name' => 'section_cta_link',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551eb749ac1f6',
								'label' => 'Full width CTA button?',
								'name' => 'section_cta_full',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_551eb95b1e466',
								'label' => 'CTA icon class',
								'name' => 'section_cta_icon',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551c6a32d2fdd',
								'label' => 'Colored background?',
								'name' => 'has_bg_color',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_55ca3059315f1',
								'label' => 'Text alignment',
								'name' => 'text_alignment',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'center' => 'Center',
									'left' => 'Left',
									'right' => 'Right',
								),
								'default_value' => 'center',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_55ca30de5b286',
								'label' => 'Larger column title?',
								'name' => 'has_col_title_lg',
								'type' => 'true_false',
								'instructions' => 'Should the column titles be a larger font size than the body?',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_55ca39ae48e87',
								'label' => 'Border dividers?',
								'name' => 'has_border_dividers',
								'type' => 'true_false',
								'instructions' => 'Should the columns be divided by lines?',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_551ac2d1e1c80',
								'label' => 'Column',
								'name' => 'icon_column',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_551c4f024e907',
										'label' => 'Title',
										'name' => 'icon_col_title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551ac2d1e1c81',
										'label' => 'Text',
										'name' => 'icon_col_text',
										'type' => 'wysiwyg',
										'column_width' => '',
										'default_value' => '',
										'toolbar' => 'basic',
										'media_upload' => 'no',
									),
									array (
										'key' => 'field_551ac2d1e1c83',
										'label' => 'Image',
										'name' => 'icon_col_img',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
								'row_min' => 3,
								'row_limit' => 6,
								'layout' => 'row',
								'button_label' => 'Add a column',
							),
						),
					),
					array (
						'label' => 'Quarter Columns',
						'name' => 'quarter_columns',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_551c5b94a0a52',
								'label' => 'Section title',
								'name' => 'section_intro_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551c5b94a0a53',
								'label' => 'Section text',
								'name' => 'section_intro_text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_551c5b94a0a54',
								'label' => 'CTA button text',
								'name' => 'section_cta',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551eb9671e467',
								'label' => 'CTA icon class',
								'name' => 'section_cta_icon',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551c5b94a0a55',
								'label' => 'CTA Link',
								'name' => 'section_cta_link',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551ebb6f06146',
								'label' => 'Full width CTA button?',
								'name' => 'section_cta_full',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_551c5b94a0a56',
								'label' => 'Column',
								'name' => 'icon_column',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_551c5b94a0a57',
										'label' => 'Title',
										'name' => 'icon_col_title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551c5b94a0a58',
										'label' => 'Text',
										'name' => 'icon_col_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551c5b94a0a59',
										'label' => 'Image',
										'name' => 'icon_col_img',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
								'row_min' => 4,
								'row_limit' => 4,
								'layout' => 'row',
								'button_label' => 'Add a column',
							),
							array (
								'key' => 'field_551c6a7108038',
								'label' => 'Gray background?',
								'name' => 'bg_gray',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
						),
					),
					array (
						'label' => 'Fifth Columns',
						'name' => 'fifth_columns',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_55481033bba78',
								'label' => 'Section title',
								'name' => 'section_intro_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_55481033bba79',
								'label' => 'Section text',
								'name' => 'section_intro_text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_55481033bba7a',
								'label' => 'CTA button text',
								'name' => 'section_cta',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_55481033bba7b',
								'label' => 'CTA icon class',
								'name' => 'section_cta_icon',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_55481033bba7c',
								'label' => 'CTA Link',
								'name' => 'section_cta_link',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_55481033bba7d',
								'label' => 'Full width CTA button?',
								'name' => 'section_cta_full',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_55481033bba7e',
								'label' => 'Column',
								'name' => 'icon_column',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_55481033bba7f',
										'label' => 'Title',
										'name' => 'icon_col_title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_55481033bba80',
										'label' => 'Text',
										'name' => 'icon_col_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_55481033bba81',
										'label' => 'Image',
										'name' => 'icon_col_img',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
								'row_min' => 5,
								'row_limit' => 5,
								'layout' => 'row',
								'button_label' => 'Add a column',
							),
							array (
								'key' => 'field_55481033bba82',
								'label' => 'Gray background?',
								'name' => 'bg_gray',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
						),
					),
					array (
						'label' => 'Icon Columns (Halves)',
						'name' => 'icon_columns',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_55cb8298369c3',
								'label' => 'Border?',
								'name' => 'section_border',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'' => '',
									'top' => 'Top',
									'bottom' => 'Bottom',
									'both' => 'Both',
								),
								'default_value' => 'top',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_55cb8320369c4',
								'label' => 'No top padding?',
								'name' => 'no_top_padding',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_55ca3347adce5',
								'label' => 'Section title',
								'name' => 'section_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551add1a07700',
								'label' => 'Icon',
								'name' => 'icon_column',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_551ae5a4d4765',
										'label' => 'Title',
										'name' => 'icon_col_title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551add1a07701',
										'label' => 'Text',
										'name' => 'icon_col_text',
										'type' => 'wysiwyg',
										'column_width' => '',
										'default_value' => '',
										'toolbar' => 'basic',
										'media_upload' => 'no',
									),
									array (
										'key' => 'field_551add1a07702',
										'label' => 'Image',
										'name' => 'icon_col_img',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
								'row_min' => 2,
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add a column',
							),
							array (
								'key' => 'field_551c371beafca',
								'label' => 'CTA button text',
								'name' => 'section_cta',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551c372eeafcb',
								'label' => 'CTA button link',
								'name' => 'section_cta_link',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551eb735ac1f5',
								'label' => 'CTA icon class',
								'name' => 'section_cta_icon',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_551ebba7c40dd',
								'label' => 'Full width CTA button?',
								'name' => 'section_cta_full',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_5578a6112d98c',
								'label' => 'CTA button #2 Text',
								'name' => 'section_cta2',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5578a6322d98d',
								'label' => 'CTA button #2 link',
								'name' => 'section_cta2_link',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5578a6542d98e',
								'label' => 'CTA button #2 icon class',
								'name' => 'section_cta2_icon',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_55cbcfac4f5f9',
								'label' => 'Skinny columns?',
								'name' => 'is_column_slim',
								'type' => 'true_false',
								'instructions' => 'In desktop view, should the columns be slimmed down and centered?',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
						),
					),
					array (
						'label' => 'Careers',
						'name' => 'careers',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
						),
					),
					array (
						'label' => 'Image Links',
						'name' => 'image_block_links',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_551d5a880fce6',
								'label' => 'Image Link',
								'name' => 'image_links',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_551d5aa90fce7',
										'label' => 'Image',
										'name' => 'image_link_img',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_551d5b040fce8',
										'label' => 'Link',
										'name' => 'image_link_url',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_551d5b310fce9',
										'label' => 'Text',
										'name' => 'image_link_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add Row',
							),
						),
					),
					array (
						'label' => 'Video Embed',
						'name' => 'video_embed',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_55c8ce9d74b09',
								'label' => 'HTML iframe',
								'name' => 'html_iframe',
								'type' => 'textarea',
								'instructions' => 'Everything is rendered as HTML, including iframes, script tags, etc.	Be careful!	WordPress strips this stuff out by default, for good reason--if you don\'t know what you\'re doing you can easily create a security issue, break the site, etc.',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '<iframe></iframe><script></script>',
								'maxlength' => '',
								'rows' => '',
								'formatting' => 'html',
							),
							array (
								'key' => 'field_55dc87d80fd5e',
								'label' => 'Border?',
								'name' => 'section_border',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'' => '',
									'top' => 'Top',
									'bottom' => 'Bottom',
									'both' => 'Both',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
						),
					),
					array (
						'label' => 'White Space',
						'name' => 'whitespace',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
						),
					),
					array (
						'label' => 'Raw HTML',
						'name' => 'raw_html',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_552348d29e127',
								'label' => 'HTML',
								'name' => 'html',
								'type' => 'textarea',
								'instructions' => 'Everything is rendered as HTML, including iframes, script tags, etc.	Be careful!	WordPress strips this stuff out by default, for good reason--if you don\'t know what you\'re doing you can easily create a security issue, break the site, etc.',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'formatting' => 'html',
							),
						),
					),
					array (
						'label' => 'Video Menu',
						'name' => 'video_menu',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5775478fa844d',
								'label' => 'Featured Video',
								'name' => 'featured_video',
								'type' => 'text',
								'instructions' => 'ID of the video you want to feature at the top; take from end of wistia URL',
								'required' => 1,
								'column_width' => '',
								'default_value' => '',
								'placeholder' => 'asd14f1d37',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_577540a2d8ca4',
								'label' => 'Visible Video',
								'name' => 'visible_video',
								'type' => 'repeater',
								'instructions' => 'Videos that are always visible on page',
								'required' => 1,
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_577540b6d8ca5',
										'label' => 'Visible Video Title',
										'name' => 'visible_video_title',
										'type' => 'text',
										'required' => 1,
										'column_width' => '',
										'default_value' => '',
										'placeholder' => 'Title of the visible video',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_57754148d8ca6',
										'label' => 'Visible Video Description',
										'name' => 'visible_video_description',
										'type' => 'textarea',
										'instructions' => 'Description of the visible video',
										'required' => 1,
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'formatting' => 'html',
									),
									array (
										'key' => 'field_5775417dd8ca7',
										'label' => 'Visible Video ID',
										'name' => 'visible_video_id',
										'type' => 'text',
										'instructions' => 'Wistia video ID. Take from end of wistia URL.',
										'required' => 1,
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => 1,
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_577541b8d8ca8',
								'label' => 'Hidden Video',
								'name' => 'hidden_video',
								'type' => 'repeater',
								'instructions' => 'Videos that can be shown or hidden on page',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_577541e5d8ca9',
										'label' => 'Hidden Video Title',
										'name' => 'hidden_video_title',
										'type' => 'text',
										'required' => 1,
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_577541fbd8caa',
										'label' => 'Hidden Video Description',
										'name' => 'hidden_video_description',
										'type' => 'textarea',
										'required' => 1,
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'formatting' => 'br',
									),
									array (
										'key' => 'field_5775420bd8cab',
										'label' => 'Hidden Video ID',
										'name' => 'hidden_video_id',
										'type' => 'text',
										'instructions' => 'Wistia video ID. Take from end of wistia URL.',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Row',
							),
						),
					),
				),
				'button_label' => 'Add a content block',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}



?>